
export  const courses = [
    {
      id: 1,
      title: 'Learn Figma - UI/UX Design Essential Training',
      imgSrc: '/assets/coursesCards/1.png',
      lessons: 6,
      duration: '3h 56m',
      level: 'Beginner',
    },
    {
      id: 2,
      title: 'Complete Python Bootcamp From Zero to Hero in Python',
      imgSrc: '/assets/coursesCards/2.png',
      lessons: 6,
      duration: '3h 56m',
      level: 'Beginner',
    },
    {
      id: 3,
      title: 'Angular - The Complete Guide (2022 Edition)',
      imgSrc: '/assets/coursesCards/3.png',
      lessons: 6,
      duration: '3h 56m',
      level: 'Beginner',
    },
    {
      id: 4,
      title: 'The Ultimate Drawing Course Beginner to Advanced',
      imgSrc: '/assets/coursesCards/4.png',
      lessons: 6,
      duration: '3h 56m',
      level: 'Beginner',
    },
    {
      id: 5,
      title: 'Photography Masterclass: A Complete Guide to Photography',
      imgSrc: '/assets/coursesCards/5.png',
      lessons: 6,
      duration: '3h 56m',
      level: 'Beginner',
    },
    {
      id: 6,
      title: 'Instagram Marketing 2021: Complete Guide To Instagram',
      imgSrc: '/assets/coursesCards/6.png',
      lessons: 6,
      duration: '3h 56m',
      level: 'Beginner',
    },
    {
      id: 7,
      title: 'Complete Blender Creator: Learn 3D Modelling for Beginners',
      imgSrc: '/assets/coursesCards/7.png',
      lessons: 6,
      duration: '3h 56m',
      level: 'Beginner',
    },
    {
      id: 8,
      title: 'The Complete Financial Analyst Training & Investing Course',
      imgSrc: '/assets/coursesCards/8.png',
      lessons: 6,
      duration: '3h 56m',
      level: 'Beginner',
    },
  ];